### ISSUE TITLE
Project Discovery + Planning

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/north-texas-evictions#2]
# Tasks

- [x] identify target audiences
- [x] identify use cases / goals
- [x] write functional specification
- [x] determine client deliverables
- [x] create data plan
- [x] create road map

**Comment by Lane** [comment]
- [Target audiences, use cases, functional spec, client deliverables](https://docs.google.com/document/d/1oDAj2J7TTpUeO-fv-Dq6VKZ1hcOS1l7S8NxdQPv60kU/edit#heading=h.tj1q20f3pq9c)
- [Data Plan](https://github.com/Hyperobjekt/north-texas-evictions/files/6903019/nte-data-plan.1.pdf)
