### ISSUE TITLE
Add date pickers to data options panel

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/north-texas-evictions#32]
Currently, the data options panel has basic text inputs for date entry.  These should be replaced by the material UI date picker, and placed side by side as seen in the mockup:

![image](https://user-images.githubusercontent.com/21034/132393664-60e648d6-6096-4b44-80dd-1c2dfc7f8f6f.png)

## Tasks

- [ ] create a generic date picker component using the [material ui picker](https://material-ui.com/components/pickers/)
- [ ] create a start date picker component that is connected to the dashboard store (useDashboardStore)
  - [ ] displays the current selected start date (`activeDateRange[0]` from the store)
  - [ ] updates the start date when a new value is picked 
  - [ ] allows manual entry of date
  - [ ] only allows selecting / entry of dates that are within the allowed date range (`dateRange` from the store)
- [ ] create a end date picker component that is connected to the dashboard store (useDashboardStore)
  - [ ] displays the current selected end date (`activeDateRange[1]` from the store)
  - [ ] updates the end date when a new value is picked 
  - [ ] allows manual entry of date
  - [ ] only allows selecting / entry of dates that are within the allowed date range (`dateRange` from the store)
- [ ] dates are formatted as `YYYY-MM-DD`
- [ ] add the start date / end date picker components to the data options panel (as seen in the mockup)
