### ISSUE TITLE
Add conditional map notes to legend

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/north-texas-evictions#35]
# Tasks

- [ ] determine which conditions should display a data note (discuss w/ Owen)
- [ ] add a configuration entry for data notes that specifies the conditions and the note to display
- [ ] add logic to check the dashboard state and compare it to the configuration entries, and display the note if it matches.

**Example**:

```jsx
<App config={{
  // ...
  flags: [
    { 
      conditions: { activeBubble: "mfa" }, // matches when active bubble is median filing amount
      note: "Median filing amounts are only available for Dallas County." 
    },
    // ...
  ],
  // ...
}} />
```

![image](https://user-images.githubusercontent.com/21034/132406886-eef6ffe5-f964-4eb2-8a3e-ca2dc76f1337.png)
