### ISSUE TITLE
Allow different choropleth metric scale types

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/north-texas-evictions#36]
currently all choropleth metrics are continuous linear scales.

sometimes a quantized scale may be more suitable to handle outliers, so we should allow this via configuration.

## Tasks

- [ ] update metric configuration in the app config to allow specifying the scale type (e.g. "continuous" or "quantize")
- [ ] update the map style to use quantized colors when quantize is specified
- [ ] update the map legend to display a quantize scale when quantize is specified for a metric
