### ISSUE TITLE
Add "data last updated" date

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/north-texas-evictions#37]
the legend should indicate the date last updated.

# Tasks

- [x] allow retrieving the last updated date from API or static file (backend)
- [ ] fetch the last updated date from the backend, display in the legend
- [ ] use the last updated date as a reference point for date shortcuts (last 7 days, last 30 days, etc.)

**Comment by Lane** [comment]
@touchRED you can get the first and last filing date from this endpoint:

https://cnvdr1v7ki.execute-api.us-east-1.amazonaws.com/meta

here is a more detailed task list for this issue:

- [ ] add the last updated date to the "summary" section of the legend:

![image](https://user-images.githubusercontent.com/21034/132549555-8a8746b5-d3b5-40da-92b9-9e323f64aae2.png)

- [ ] update the `DATE_OPTIONS` in `Legend.js` to use the `last_filing` date instead of the current date for the "last `x` days" options

- [ ] update the `DATE_OPTIONS` in `Legend.js` to use the `first_filing` date and `last_filing` date for the "all time" option

- [ ] update the summary "overline" to include the date range currently being viewed (as seen in figma)

![image](https://user-images.githubusercontent.com/21034/132549914-8efd81b1-6b89-4445-a566-305d9e850892.png)

- [ ] update the `dateRange` in the store to be [first_filing, last_filing] to set the range of valid dates
