### ISSUE TITLE
Add "About" page

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/north-texas-evictions#38]
## Objective
Add an about the data page with attribution, data limitations, FAQ, etc. as follows: 
- About eviction
     - What is the eviction process?
     - How does eviction impact kids and their families?
- About the data/methods/FAQ
- How to use the data / applications of the data

Notes
- This will be a single page integrated into the tool
- CPAL team to provide content for this page
- Sasha to determine best implementation plan

# Tasks

- [ ] (client) get about page content from Ashley
- [ ] determine best implementation plan (dialog overlay or page level routing w/ menu)
- [ ] write spec
- [ ] design (if needed)
- [ ] client approval

# Resources
[Content & Copy](https://docs.google.com/document/d/1iiC6okLOY5xYRWBpngeM7Brh0fX9SeaCWqUrtU_fUd4/edit?usp=sharing)
