### ISSUE TITLE
handle choropleth metrics that are not available

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/north-texas-evictions#48]
Some choropleth metrics are not available at certain regions.  

# Tasks

- [x] add a flag note when switching to a region where the metric is not available
- [x] add configuration to metrics to indicate which regions they are unavailable for
- [x] update the select menu to have a category for "unavailable metrics" that are all disabled (changes by region)
