### ISSUE TITLE
Add JP Precinct Region

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/north-texas-evictions#74]
## Objective
Add Justice of the Peace (JP) Precinct boundaries as a region. 
- Add JP bounds as region (waiting on CPAL team to provide JP geojson shaped files) 
- Remove court filter once JP region is added

## Background
Request from Ashley via email:
>I wonder if the JP Courts should be a drop-down in the "Region" instead of its own thing. It's a little confusing that selection of JP court is separate. Owen, do we have the shape files for the JP court jurisdictions in the other counties? Is this why it's a separate thing?

**Comment by Lane** [comment]
## Spec

- the region selection has an additional option for Justice of the Peace Precincts
- when selecting the "Justice of the Peace Precincts" option, the map updates to show data for this corresponding region

## Tasks

- [ ] add app configuration for the new region, including a reference to choropleth GeoJSON file, bubbles GeoJSON file.
- [ ] add required language strings to the app configuration
- [ ] adjust the backend API to allow grouping of eviction data by Justice of the Peace Precinct
- [ ] Remove existing court filtering functionality
