### ISSUE TITLE
Add JP Precinct Region

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/north-texas-evictions#89]
## Objective
Add JP Precinct as an additional region to explorer. 

## Dependencies
Waiting on CPAL to provide geojson by Friday, October 15

## Spec

- the region selection has an additional option for Justice of the Peace Precincts
- when selecting the "Justice of the Peace Precincts" option, the map updates to show data for this corresponding region

## Tasks

- [ ] add app configuration for the new region, including a reference to choropleth GeoJSON file, bubbles GeoJSON file.
- [ ] add required language strings to the app configuration
- [ ] adjust the backend API to allow grouping of eviction data by Justice of the Peace Precinct
- [ ] Remove existing court filtering functionality
